{
  "main": ".worker-next/worker.js",
  "name": "ecommerce",
  "compatibility_date": "2024-09-23",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": ".worker-next/assets",
    "binding": "ASSETS"
  }
}